import type React from 'react';
import type {
  FadhilWebCompiledSyntax,
  FadhilWebFlatSyntaxObject,
  FadhilWebSyntax,
  ResolvedSyntax,
  ResolvedSyntaxLogic,
  ResolvedSyntaxSemantics,
  SyntaxScalar,
} from '../types';

export const MAX_CACHE_SIZE = 250;
export const parsedStringSyntaxCache = new Map<string, FadhilWebFlatSyntaxObject>();
export const resolvedStringSyntaxCache = new Map<string, ResolvedSyntax>();
export const parsedObjectSyntaxCache = new WeakMap<object, FadhilWebFlatSyntaxObject>();
export const resolvedObjectSyntaxCache = new WeakMap<object, ResolvedSyntax>();

export const EMPTY_PARSED_SYNTAX = Object.freeze({}) as FadhilWebFlatSyntaxObject;
export const EMPTY_STYLE = Object.freeze({}) as React.CSSProperties;
export const EMPTY_SEMANTICS = Object.freeze({}) as ResolvedSyntaxSemantics;
export const EMPTY_LOGIC = Object.freeze({}) as ResolvedSyntaxLogic;
export const EMPTY_ATTRS = Object.freeze({}) as Record<string, SyntaxScalar>;
export const EMPTY_RESOLVED_SYNTAX = Object.freeze({
  style: EMPTY_STYLE,
  semantics: EMPTY_SEMANTICS,
  logic: EMPTY_LOGIC,
  attrs: EMPTY_ATTRS,
}) as ResolvedSyntax;

export type CanonicalSyntaxKey = keyof FadhilWebFlatSyntaxObject;
export type CanonicalSyntaxGroupName =
  | 'layout'
  | 'spacing'
  | 'surface'
  | 'text'
  | 'fx'
  | 'logic'
  | 'aria'
  | 'data'
  | 'vars'
  | 'css'
  | 'attrs';

export const KEY_ALIASES: Record<string, CanonicalSyntaxKey> = {
  tone: 'tone',
  size: 'size',
  density: 'density',
  compact: 'compact',
  full: 'full',
  fullwidth: 'full',
  bg: 'bg',
  background: 'bg',
  gradient: 'gradient',
  gradienttext: 'gradientText',
  gtext: 'gradientText',
  bgimage: 'bgImage',
  bgsize: 'bgSize',
  bgposition: 'bgPosition',
  bgpos: 'bgPosition',
  bgrepeat: 'bgRepeat',
  bgclip: 'bgClip',
  bgorigin: 'bgOrigin',
  fg: 'fg',
  color: 'fg',
  border: 'border',
  bordercolor: 'border',
  bw: 'borderWidth',
  borderwidth: 'borderWidth',
  bs: 'borderStyle',
  borderstyle: 'borderStyle',
  shadow: 'shadow',
  ring: 'ring',
  ringcolor: 'ringColor',
  ringoffset: 'ringOffset',
  ringoffsetcolor: 'ringOffsetColor',
  radius: 'radius',
  r: 'radius',
  outlinecolor: 'outlineColor',
  outlinewidth: 'outlineWidth',
  outlineoffset: 'outlineOffset',
  gap: 'gap',
  p: 'p',
  px: 'px',
  py: 'py',
  pt: 'pt',
  pr: 'pr',
  pb: 'pb',
  pl: 'pl',
  m: 'm',
  mx: 'mx',
  my: 'my',
  mt: 'mt',
  mr: 'mr',
  mb: 'mb',
  ml: 'ml',
  w: 'w',
  width: 'w',
  h: 'h',
  height: 'h',
  minw: 'minW',
  maxw: 'maxW',
  minh: 'minH',
  maxh: 'maxH',
  fs: 'fontSize',
  fontsize: 'fontSize',
  font: 'fontSize',
  ff: 'fontFamily',
  fontfamily: 'fontFamily',
  fw: 'weight',
  weight: 'weight',
  lh: 'lineHeight',
  lineheight: 'lineHeight',
  tracking: 'tracking',
  ls: 'tracking',
  textalign: 'textAlign',
  ta: 'textAlign',
  texttransform: 'textTransform',
  whitespace: 'whiteSpace',
  ws: 'whiteSpace',
  textwrap: 'textWrap',
  wraptext: 'textWrap',
  truncate: 'truncate',
  clamp: 'clampLines',
  clamplines: 'clampLines',
  opacity: 'opacity',
  accent: 'accent',
  accentcolor: 'accent',
  caret: 'caret',
  caretcolor: 'caret',
  display: 'display',
  direction: 'direction',
  dir: 'direction',
  wrap: 'wrap',
  align: 'align',
  justify: 'justify',
  self: 'self',
  grow: 'grow',
  shrink: 'shrink',
  basis: 'basis',
  order: 'order',
  ord: 'order',
  cols: 'cols',
  columns: 'cols',
  rows: 'rows',
  autoflow: 'autoFlow',
  autocols: 'autoCols',
  autorows: 'autoRows',
  placeitems: 'placeItems',
  placecontent: 'placeContent',
  justifyitems: 'justifyItems',
  justifyself: 'justifySelf',
  gridcolumn: 'gridColumn',
  gridrow: 'gridRow',
  templateareas: 'templateAreas',
  areas: 'templateAreas',
  area: 'area',
  colspan: 'colSpan',
  rowspan: 'rowSpan',
  aspect: 'aspect',
  aspectratio: 'aspect',
  overflow: 'overflow',
  overflowx: 'overflowX',
  ox: 'overflowX',
  overflowy: 'overflowY',
  oy: 'overflowY',
  overscroll: 'overscroll',
  overscrollx: 'overscrollX',
  overscrolly: 'overscrollY',
  scrollbehavior: 'scrollBehavior',
  scrollsnaptype: 'scrollSnapType',
  snaptype: 'scrollSnapType',
  scrollsnapalign: 'scrollSnapAlign',
  snapalign: 'scrollSnapAlign',
  scrollsnapstop: 'scrollSnapStop',
  snapstop: 'scrollSnapStop',
  scrollmargin: 'scrollMargin',
  scrollmarginx: 'scrollMarginX',
  scrollmarginy: 'scrollMarginY',
  scrollpadding: 'scrollPadding',
  scrollpaddingx: 'scrollPaddingX',
  scrollpaddingy: 'scrollPaddingY',
  scrollbargutter: 'scrollbarGutter',
  position: 'position',
  pos: 'position',
  inset: 'inset',
  top: 'top',
  right: 'right',
  bottom: 'bottom',
  left: 'left',
  z: 'z',
  zindex: 'z',
  sticky: 'sticky',
  pin: 'pin',
  cursor: 'cursor',
  pointerevents: 'pointerEvents',
  pe: 'pointerEvents',
  userselect: 'userSelect',
  filter: 'filter',
  backdrop: 'backdrop',
  backdropfilter: 'backdrop',
  blend: 'blend',
  mixblendmode: 'blend',
  isolation: 'isolation',
  transform: 'transform',
  transformorigin: 'transformOrigin',
  origin: 'transformOrigin',
  transition: 'transition',
  duration: 'duration',
  ease: 'ease',
  delay: 'delay',
  animation: 'animation',
  animationduration: 'animationDuration',
  animationdelay: 'animationDelay',
  animationtiming: 'animationTiming',
  willchange: 'willChange',
  scale: 'scale',
  scalex: 'scaleX',
  scaley: 'scaleY',
  rotate: 'rotate',
  translatex: 'translateX',
  tx: 'translateX',
  translatey: 'translateY',
  ty: 'translateY',
  skewx: 'skewX',
  skewy: 'skewY',
  blur: 'blur',
  brightness: 'brightness',
  contrast: 'contrast',
  saturate: 'saturate',
  contain: 'contain',
  contentvisibility: 'contentVisibility',
  cv: 'contentVisibility',
  containintrinsicsize: 'containIntrinsicSize',
  cis: 'containIntrinsicSize',
  role: 'role',
  tabindex: 'tabIndex',
  title: 'titleText',
  titletext: 'titleText',
  inert: 'inert',
  loading: 'loading',
  disabled: 'disabled',
  open: 'open',
  hidden: 'hidden',
  current: 'current',
  interactive: 'interactive',
  focusable: 'focusable',
  visuallyhidden: 'visuallyHidden',
  sronly: 'visuallyHidden',
  presence: 'presence',
};

export const GROUP_ALIASES: Record<string, CanonicalSyntaxGroupName> = {
  ui: 'surface',
  layout: 'layout',
  arrange: 'layout',
  flow: 'layout',
  spacing: 'spacing',
  space: 'spacing',
  surface: 'surface',
  box: 'surface',
  visual: 'surface',
  text: 'text',
  typography: 'text',
  fx: 'fx',
  motion: 'fx',
  effects: 'fx',
  logic: 'logic',
  behavior: 'logic',
  aria: 'aria',
  data: 'data',
  vars: 'vars',
  css: 'css',
  attrs: 'attrs',
  attr: 'attrs',
};

export const GROUP_KEYS = {
  layout: [
    'display',
    'direction',
    'wrap',
    'align',
    'justify',
    'self',
    'gap',
    'grow',
    'shrink',
    'basis',
    'order',
    'cols',
    'rows',
    'autoFlow',
    'autoCols',
    'autoRows',
    'placeItems',
    'placeContent',
    'justifyItems',
    'justifySelf',
    'gridColumn',
    'gridRow',
    'templateAreas',
    'area',
    'colSpan',
    'rowSpan',
    'aspect',
    'w',
    'h',
    'minW',
    'maxW',
    'minH',
    'maxH',
    'overflow',
    'overflowX',
    'overflowY',
    'overscroll',
    'overscrollX',
    'overscrollY',
    'scrollBehavior',
    'scrollSnapType',
    'scrollSnapAlign',
    'scrollSnapStop',
    'scrollMargin',
    'scrollMarginX',
    'scrollMarginY',
    'scrollPadding',
    'scrollPaddingX',
    'scrollPaddingY',
    'scrollbarGutter',
    'position',
    'inset',
    'top',
    'right',
    'bottom',
    'left',
    'z',
    'sticky',
    'pin',
  ],
  spacing: [
    'gap',
    'p',
    'px',
    'py',
    'pt',
    'pr',
    'pb',
    'pl',
    'm',
    'mx',
    'my',
    'mt',
    'mr',
    'mb',
    'ml',
  ],
  surface: [
    'tone',
    'size',
    'density',
    'compact',
    'full',
    'bg',
    'gradient',
    'gradientText',
    'bgImage',
    'bgSize',
    'bgPosition',
    'bgRepeat',
    'bgClip',
    'bgOrigin',
    'fg',
    'border',
    'borderWidth',
    'borderStyle',
    'shadow',
    'ring',
    'ringColor',
    'ringOffset',
    'ringOffsetColor',
    'radius',
    'outlineColor',
    'outlineWidth',
    'outlineOffset',
    'opacity',
  ],
  text: [
    'fontSize',
    'fontFamily',
    'weight',
    'lineHeight',
    'tracking',
    'textAlign',
    'textTransform',
    'whiteSpace',
    'textWrap',
    'truncate',
    'clampLines',
    'accent',
    'caret',
  ],
  fx: [
    'cursor',
    'pointerEvents',
    'userSelect',
    'filter',
    'backdrop',
    'blend',
    'isolation',
    'transform',
    'transformOrigin',
    'transition',
    'duration',
    'ease',
    'delay',
    'animation',
    'animationDuration',
    'animationDelay',
    'animationTiming',
    'willChange',
    'scale',
    'scaleX',
    'scaleY',
    'rotate',
    'translateX',
    'translateY',
    'skewX',
    'skewY',
    'blur',
    'brightness',
    'contrast',
    'saturate',
    'contain',
    'contentVisibility',
    'containIntrinsicSize',
  ],
  logic: [
    'role',
    'tabIndex',
    'titleText',
    'inert',
    'loading',
    'disabled',
    'open',
    'hidden',
    'current',
    'interactive',
    'focusable',
    'visuallyHidden',
    'presence',
  ],
} as const satisfies Record<'layout' | 'spacing' | 'surface' | 'text' | 'fx' | 'logic', readonly CanonicalSyntaxKey[]>;

export const GROUP_KEY_SETS = Object.freeze({
  layout: new Set<CanonicalSyntaxKey>(GROUP_KEYS.layout),
  spacing: new Set<CanonicalSyntaxKey>(GROUP_KEYS.spacing),
  surface: new Set<CanonicalSyntaxKey>(GROUP_KEYS.surface),
  text: new Set<CanonicalSyntaxKey>(GROUP_KEYS.text),
  fx: new Set<CanonicalSyntaxKey>(GROUP_KEYS.fx),
  logic: new Set<CanonicalSyntaxKey>(GROUP_KEYS.logic),
});

export const BOOLEAN_TRUE = new Set(['true', '1', 'yes', 'on', 'wrap']);
export const BOOLEAN_FALSE = new Set(['false', '0', 'no', 'off', 'nowrap']);

export function rememberCache<T>(cache: Map<string, T>, key: string, value: T) {
  if (cache.has(key)) {
    cache.delete(key);
  } else if (cache.size >= MAX_CACHE_SIZE) {
    const firstKey = cache.keys().next().value;
    if (firstKey) {
      cache.delete(firstKey);
    }
  }

  cache.set(key, value);
}

export function normalizeKey(rawKey: string) {
  return KEY_ALIASES[rawKey.trim().toLowerCase()];
}

export function normalizeGroupName(rawGroup: string) {
  return GROUP_ALIASES[rawGroup.trim().toLowerCase()];
}

export function isKnownGroupKey(
  group: Exclude<CanonicalSyntaxGroupName, 'aria' | 'data' | 'vars' | 'css' | 'attrs'>,
  key: CanonicalSyntaxKey,
) {
  return GROUP_KEY_SETS[group].has(key);
}

export function isCompiledSyntax(input: FadhilWebSyntax): input is FadhilWebCompiledSyntax {
  return typeof input === 'object' && input !== null && '__fwlbType' in input && input.__fwlbType === 'compiled-syntax';
}

export function freezeResolvedSyntax(
  style: React.CSSProperties,
  semantics: ResolvedSyntaxSemantics,
  logic: ResolvedSyntaxLogic,
  attrs: Record<string, SyntaxScalar>,
) {
  return Object.freeze({
    style: Object.freeze(style) as React.CSSProperties,
    semantics: Object.freeze(semantics) as ResolvedSyntaxSemantics,
    logic: Object.freeze(logic) as ResolvedSyntaxLogic,
    attrs: Object.freeze(attrs) as Record<string, SyntaxScalar>,
  }) as ResolvedSyntax;
}
