provider = "postgresql"
formatVersion = "1.0.0"
version = "5.22.0"

[[migrations]]
checksum = "8cafefd90f66f03c9cf24a4b49c80d6b1ffa50b97a50ac3c95cb21e6cc54e8f8"
finished_at = ""
migration_name = "0_init"
logs = ""
rolled_back_at = ""
started_at = "2026-02-10T19:00:00.000Z"
applied_steps_count = 0
